name: Mirror Fork

on:
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches and tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Git config
        run: |
          git config --global user.name "Ved"
          git config --global user.email "ved.pawar2024@nst.rishihood.edu.in"

      - name: Add fork remote and push all refs
        env:
          PAT: ${{ secrets.PAT_TO_PUSH }}
        run: |
          git remote add fork https://vedpawar2254:${PAT}@github.com/devclub-nstru/Sevi.git
          git push fork --mirror
